# Generated by Django 5.0.6 on 2024-05-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceHeaderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoiceNumber', models.IntegerField()),
                ('customerName', models.CharField(max_length=42)),
                ('billingAddress', models.CharField(max_length=50)),
                ('shippingAddress', models.CharField(max_length=50)),
                ('gstin', models.CharField(max_length=50)),
                ('totalAmount', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': 'InvoiceHeaderModel',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItemsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=32)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': 'InvoiceItemsModel',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSundry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billSundryName', models.CharField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': 'InvoiceSundry',
            },
        ),
        migrations.DeleteModel(
            name='SchoolModel',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
