# Generated by Django 5.0.6 on 2024-05-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_invoiceheadermodel_invoiceitemsmodel_invoicesundry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheadermodel',
            name='date',
            field=models.DateField(auto_created=True),
        ),
    ]
